"""LiteLLM proxy custom callbacks.

Loaded by the homelab model gateway via:

    litellm_settings:
      callbacks: custom_callbacks.proxy_handler_instance

Two responsibilities, both implemented on the same logger object:

  1. **CostJsonlHandler** — append one JSON line per completed call to
     ``$LLM_CALLS_JSONL`` (default ``/var/log/llm-calls/llm-calls.jsonl``).
     This is the original Phase 0.6 behaviour.
  2. **Local-only enforcement** — Phase 1 finance prereq P1. The pre-call
     hook reads the ``x-skill`` header, looks up the skill in a snapshot of
     ``config/skills/`` (generated by ``generate_skill_policy.py`` at gateway
     start), and rejects the request with an LLM-friendly 403 if the skill
     is ``local_only=true`` but the requested model is not on a local route.
     An audit JSONL row with ``status="rejected_local_only"`` is appended so
     the cost relay surfaces the rejection in the master dashboard.

Design notes
------------
- Writes are best-effort and never raise into the request path. A logging
  failure here must never break an LLM call. The proxy will catch
  exceptions, but we belt-and-suspenders it with broad try/except.
- The record schema is the contract with ``apps/litellm_cost_relay/``;
  evolve via ``schema`` field bumps, not silent column renames.
- ``agent_principal`` is sourced from the ``x-agent-principal`` header set
  by ``apps/_shared/rlm/subcall.py``. Falls back to ``"unknown"``.
- ``request_id`` from the ``x-litellm-call-id`` header (proxy-assigned) so
  the same call can be cross-referenced in agent ledgers later.
- ``task_intent`` from the ``x-task-intent`` header (set by
  ``apps/_shared/rlm/subcall.py`` per sub-call). Lets us group cost/latency
  by task class (summarize / classify / code / plan) in the dashboard.
  Null when the caller doesn't supply it (e.g. direct API hits without
  the RLM harness).
- We extract ``response_cost`` opportunistically: LiteLLM auto-computes
  it for catalogued models, but our self-hosted vLLM models will yield
  ``0.0``. That is fine — token counts are the real signal locally.
"""

from __future__ import annotations

import json
import os
import sys
import threading
import time
from pathlib import Path
from typing import Any, Mapping

# When the tests load this as ``apps._shared.litellm_callbacks.custom_callbacks``
# (package import), the relative import works. When the LiteLLM proxy loads
# this from ``/app/custom_callbacks.py`` inside the container, there is no
# package context — both files sit at /app/ as top-level modules — so we fall
# back to a non-package import. The systemd unit bind-mounts both files into
# /app/, so the absolute import resolves there.
try:
    from .local_only_policy import (
        LocalOnlyViolation,
        PolicySnapshot,
        check_call,
        load_snapshot,
    )
except ImportError:
    from local_only_policy import (  # type: ignore[no-redef]
        LocalOnlyViolation,
        PolicySnapshot,
        check_call,
        load_snapshot,
    )

DEFAULT_PATH = "/var/log/llm-calls/llm-calls.jsonl"
SCHEMA_VERSION = 1

_write_lock = threading.Lock()


def _safe_int(value: Any) -> int | None:
    try:
        return int(value)
    except (TypeError, ValueError):
        return None


def _safe_float(value: Any) -> float | None:
    try:
        return float(value)
    except (TypeError, ValueError):
        return None


def _epoch(ts: Any) -> float | None:
    """Coerce LiteLLM's datetime-ish ``start_time``/``end_time`` to epoch seconds."""
    if ts is None:
        return None
    if isinstance(ts, (int, float)):
        return float(ts)
    timestamp = getattr(ts, "timestamp", None)
    if callable(timestamp):
        try:
            return float(timestamp())
        except Exception:
            return None
    return None


def _proxy_request(kwargs: Mapping[str, Any]) -> Mapping[str, Any]:
    params = kwargs.get("litellm_params") or {}
    request_obj = params.get("proxy_server_request") if isinstance(params, Mapping) else None
    return request_obj if isinstance(request_obj, Mapping) else {}


def _header(req: Mapping[str, Any], name: str) -> str | None:
    headers = req.get("headers") if isinstance(req, Mapping) else None
    if not isinstance(headers, Mapping):
        return None
    lowered = name.lower()
    for key, value in headers.items():
        if isinstance(key, str) and key.lower() == lowered and isinstance(value, str):
            return value
    return None


def _usage(response_obj: Any) -> dict[str, Any]:
    usage = None
    if isinstance(response_obj, Mapping):
        usage = response_obj.get("usage")
    else:
        usage = getattr(response_obj, "usage", None)
    if usage is None:
        return {}
    if isinstance(usage, Mapping):
        return dict(usage)
    return {
        "prompt_tokens": getattr(usage, "prompt_tokens", None),
        "completion_tokens": getattr(usage, "completion_tokens", None),
        "total_tokens": getattr(usage, "total_tokens", None),
    }


def build_record(
    kwargs: Mapping[str, Any],
    response_obj: Any,
    start_time: Any,
    end_time: Any,
    *,
    status: str,
    error: str | None = None,
) -> dict[str, Any]:
    """Pure-function builder of the JSONL record. Easy to unit test."""
    start = _epoch(start_time)
    end = _epoch(end_time)
    latency_ms = None
    if start is not None and end is not None:
        latency_ms = max(0, int(round((end - start) * 1000)))

    req = _proxy_request(kwargs)
    usage = _usage(response_obj)

    response_id = None
    if isinstance(response_obj, Mapping):
        response_id = response_obj.get("id")
    else:
        response_id = getattr(response_obj, "id", None)

    record: dict[str, Any] = {
        "schema": SCHEMA_VERSION,
        "ts": end if end is not None else time.time(),
        "status": status,
        "model": kwargs.get("model"),
        "agent_principal": _header(req, "x-agent-principal") or "unknown",
        "task_intent": _header(req, "x-task-intent"),
        "request_id": _header(req, "x-litellm-call-id")
        or _header(req, "x-request-id")
        or response_id,
        "prompt_tokens": _safe_int(usage.get("prompt_tokens")),
        "completion_tokens": _safe_int(usage.get("completion_tokens")),
        "total_tokens": _safe_int(usage.get("total_tokens")),
        "cost_usd": _safe_float(kwargs.get("response_cost")),
        "latency_ms": latency_ms,
        "user": kwargs.get("user"),
    }
    if error is not None:
        record["error"] = error[:512]
    return record


def _output_path() -> Path:
    return Path(os.environ.get("LLM_CALLS_JSONL", DEFAULT_PATH))


def _append(record: Mapping[str, Any]) -> None:
    path = _output_path()
    line = json.dumps(record, ensure_ascii=False, default=str) + "\n"
    try:
        path.parent.mkdir(parents=True, exist_ok=True)
        with _write_lock:
            with path.open("a", encoding="utf-8") as fh:
                fh.write(line)
    except Exception as exc:
        print(f"[litellm-cost-jsonl] write failed: {exc}", file=sys.stderr, flush=True)


try:
    from litellm.integrations.custom_logger import CustomLogger  # type: ignore
except Exception:
    CustomLogger = object  # type: ignore[assignment]

# LiteLLM raises this from a pre-call hook to reject the request with a
# specific HTTP status. Importing lazily so the unit tests that don't have
# litellm installed can still load this module.
try:
    from fastapi import HTTPException  # type: ignore
except Exception:
    class HTTPException(Exception):  # type: ignore[no-redef]
        def __init__(self, status_code: int, detail: str) -> None:
            super().__init__(detail)
            self.status_code = status_code
            self.detail = detail


# ---------------------------------------------------------------------------
# Snapshot cache.
#
# The skill-policy snapshot is generated at gateway start (ExecStartPre on
# alienware-model-gateway.service). We load it lazily on first pre-call hook
# invocation and cache for the gateway process lifetime; restarting the unit
# refreshes the cache. The lazy load avoids forcing the snapshot to exist
# before the callback module imports (helps test environments).
# ---------------------------------------------------------------------------


_policy_lock = threading.Lock()
_policy_snapshot: PolicySnapshot | None = None


def _get_policy_snapshot() -> PolicySnapshot:
    global _policy_snapshot
    if _policy_snapshot is None:
        with _policy_lock:
            if _policy_snapshot is None:
                _policy_snapshot = load_snapshot()
    return _policy_snapshot


def _reset_policy_snapshot_for_tests() -> None:
    """Test-only: clear the cached snapshot so a new env can take effect."""
    global _policy_snapshot
    with _policy_lock:
        _policy_snapshot = None


def _audit_local_only_rejection(
    *,
    skill_id: str,
    model: str | None,
    reason: str,
    agent_principal: str | None,
    request_id: str | None,
) -> None:
    """Append a rejection row to the cost JSONL so the cost relay surfaces it."""
    try:
        record = {
            "schema": SCHEMA_VERSION,
            "ts": time.time(),
            "status": "rejected_local_only",
            "model": model,
            "agent_principal": agent_principal or "unknown",
            "task_intent": None,
            "request_id": request_id,
            "prompt_tokens": None,
            "completion_tokens": None,
            "total_tokens": None,
            "cost_usd": None,
            "latency_ms": 0,
            "user": None,
            "rejected_skill": skill_id,
            "error": reason[:512],
        }
        _append(record)
    except Exception as exc:  # noqa: BLE001
        print(
            f"[litellm-local-only] failed to write rejection audit: {exc}",
            file=sys.stderr,
            flush=True,
        )


class CostJsonlHandler(CustomLogger):  # type: ignore[misc]
    """Append a JSON record per LLM call to ``$LLM_CALLS_JSONL``."""

    # ---- Phase 1 P1: local-only enforcement (pre-call) -----------------
    async def async_pre_call_hook(  # type: ignore[override]
        self,
        user_api_key_dict: Any = None,
        cache: Any = None,
        data: Any = None,
        call_type: str = "",
    ) -> Any:
        """Reject the call before it's dispatched if it violates local_only.

        LiteLLM invokes this for every proxy request. ``data`` is the
        OpenAI-shaped request body (dict-ish). The proxy_server_request
        wrapper carries the original FastAPI request whose headers we need.

        Returning ``None``/``data`` proceeds; raising ``HTTPException``
        short-circuits with the given status code.
        """
        try:
            if not isinstance(data, Mapping):
                return data
            req = _proxy_request({"litellm_params": data}) or data
            # The "data" dict at the proxy hook is the request payload; the
            # original FastAPI request lives one level up. Try both shapes.
            headers = {}
            if isinstance(req, Mapping):
                hdrs = req.get("headers")
                if isinstance(hdrs, Mapping):
                    headers = hdrs
            # Some LiteLLM versions also stash the body under
            # data["proxy_server_request"]["headers"]; fall back to that.
            if not headers:
                psr = data.get("proxy_server_request") if isinstance(data, Mapping) else None
                if isinstance(psr, Mapping):
                    h2 = psr.get("headers")
                    if isinstance(h2, Mapping):
                        headers = h2
            skill_id = None
            agent_principal = None
            request_id = None
            for key, value in headers.items():
                if not isinstance(key, str) or not isinstance(value, str):
                    continue
                lk = key.lower()
                if lk == "x-skill":
                    skill_id = value
                elif lk == "x-agent-principal":
                    agent_principal = value
                elif lk in ("x-litellm-call-id", "x-request-id"):
                    request_id = request_id or value
            model = data.get("model") if isinstance(data, Mapping) else None
            snapshot = _get_policy_snapshot()
            check_call(skill_id=skill_id, model=model, snapshot=snapshot)
            return data
        except LocalOnlyViolation as exc:
            _audit_local_only_rejection(
                skill_id=exc.skill_id,
                model=exc.model,
                reason=exc.reason,
                agent_principal=agent_principal,
                request_id=request_id,
            )
            raise HTTPException(status_code=403, detail=exc.reason) from exc
        except HTTPException:
            raise
        except Exception as exc:  # noqa: BLE001 - never break the request path
            print(
                f"[litellm-local-only] pre-call hook crashed: {exc}; "
                f"fail-open (allowing call)",
                file=sys.stderr,
                flush=True,
            )
            return data

    async def async_log_success_event(  # type: ignore[override]
        self, kwargs: Mapping[str, Any], response_obj: Any, start_time: Any, end_time: Any
    ) -> None:
        try:
            record = build_record(kwargs, response_obj, start_time, end_time, status="success")
            _append(record)
        except Exception as exc:
            print(f"[litellm-cost-jsonl] success handler failed: {exc}", file=sys.stderr, flush=True)

    async def async_log_failure_event(  # type: ignore[override]
        self, kwargs: Mapping[str, Any], response_obj: Any, start_time: Any, end_time: Any
    ) -> None:
        try:
            err = kwargs.get("exception") or kwargs.get("error")
            record = build_record(
                kwargs,
                response_obj,
                start_time,
                end_time,
                status="failure",
                error=str(err) if err is not None else None,
            )
            _append(record)
        except Exception as exc:
            print(f"[litellm-cost-jsonl] failure handler failed: {exc}", file=sys.stderr, flush=True)

    def log_success_event(  # type: ignore[override]
        self, kwargs: Mapping[str, Any], response_obj: Any, start_time: Any, end_time: Any
    ) -> None:
        try:
            record = build_record(kwargs, response_obj, start_time, end_time, status="success")
            _append(record)
        except Exception as exc:
            print(f"[litellm-cost-jsonl] sync success handler failed: {exc}", file=sys.stderr, flush=True)

    def log_failure_event(  # type: ignore[override]
        self, kwargs: Mapping[str, Any], response_obj: Any, start_time: Any, end_time: Any
    ) -> None:
        try:
            err = kwargs.get("exception") or kwargs.get("error")
            record = build_record(
                kwargs,
                response_obj,
                start_time,
                end_time,
                status="failure",
                error=str(err) if err is not None else None,
            )
            _append(record)
        except Exception as exc:
            print(f"[litellm-cost-jsonl] sync failure handler failed: {exc}", file=sys.stderr, flush=True)


proxy_handler_instance = CostJsonlHandler()
